### ISSUE TITLE
Not compatible with the latest build

### ISSUE THREAD

**Issue by VeXHarbinger** [ericBG/AnyfinCalculator#7]
Sorry to have to open an issue, but with the updates coming this afternoon I suppose you'll need to update this anyways.  

I do want to say thank you so much for this plugin.  I was actually considering doing the same type of plugin, I guess I'll need to devise a new idea for one.  

I'm sure once I can see it running it will be much better than the excel shit I'm currently using to track the key Murlocs I plan on.  I'm excited to see it in action

**Comment by VeXHarbinger** [comment]
I should say, I don't think it's working.  It appears enabled in the plugin list, however I don't see any Fin dmg data.  Of course I'm just guessing when and how I should see the data.

**Comment by ericBG** [comment]
It works fine for me in testing. It's meant to show on the top left corner whenever you hover over "Anyfin". Are you using the latest HDT version? There was a slight issue with it a few weeks ago, I'm not sure when it was introduced but it is fixed with the very latest HDT which didn't allow my program to work due to an error in the deck tracker code.

**Comment by ericBG** [comment]
Should be fixed with the latest release.
